### ISSUE TITLE
[0.5pt] Find external API - group task

### ISSUE THREAD

**Issue by Sonikak004** [Sonikak004/Js-capstone-project#20]
Find an API to base the development of the webapp around it. The API should allow you to
  - Get a list of items with a unique item id (or generate the unique id).
  - For a given item, get detailed information about it.
choose an APIs that doesn't need authentication. if you select an API that requires authentication, you should implement it on your own. Also, if you select an API that provides image resources your webapp will be more visual.

**Comment by badger-99** [comment]
The API we've agreed to use for this project is the [Pokemon API.](https://pokeapi.co/)

**Comment by Sonikak004** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @badger-99,

✔️ An API is Found to base the development of the webapp around it.

Your task is complete!  There is nothing else to say other than... it's time to go ahead with the project 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**Comment by Sonikak004** [comment]
Found an external API
