### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by badger-99** [Sonikak004/Js-capstone-project#21]
https://github.com/Sonikak004/Js-capstone-project/projects/1

Our team has only two members, @Sonikak004 and @badger-99.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @badger-99 and @Sonikak004,

✔️ Tasks are complete and well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sonikak004** [comment]
Kanban board setup is approved
